@baseUrl =http://localhost:7860/api/v1


POST {{baseUrl}}/form
Content-Type: application/json

{
 "name":"faizan"
}

######
GET {{baseUrl}}/list
Content-Type: application/json

######
GET {{baseUrl}}/product?id=60848c03328a91450a341f59
Content-Type: application/json